version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  nodeapp:
    image: node:18
    container_name: nodeapp
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install express kafkajs && node server.js"]
    depends_on:
      - kafka
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: kafka:9092
