version: "3.8"

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
      
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
